version: "3.3"
services:
 nightscout1:
  image: liske/cgm-remote-monitor:14.0.3
  environment:
    TZ: Asia/Shanghai
    MONGO_CONNECTION: mongodb://mongo:27017/nightscout1
    API_SECRET: nightscout2021
    BG_HIGH: 220
    BG_LOW: 60
    BG_TARGET_TOP: 180
    BG_TARGET_BOTTOM: 80
    INSECURE_USE_HTTP: "true"
    BASE_URL: 158.101.142.148
    AUTH_DEFAULT_ROLES: readable devicestatus-upload
    PUMP_FIELDS: reservoir battery status
    ENABLE: bridge loop openaps pump iob cob basal careportal sage cage delta direction devicestatus upbat timeago
    CUSTOM_TITLE: NightscoutT1
    DISPLAY_UNITS: mmol 
    TIME_FORMAT: 24
    THEME: colors
    LANGUAGE: zh_cn 
    BASAL_RENDER: default
    SHOW_PLUGINS: pump openaps
  container_name: "nightscout1"
  ports:
    - "1337:443"
  links:
    - mongo
  restart: always
  mongo:
  container_name: "mongo_db"
  image: mongo:3.6-stretch
  volumes:
    - ./mongodb:/data/db
  restart: always
